"""Compatibility exports; new DTO definitions belong in app.domain_models."""

from app.domain_models.analysis import (
    HermesIssueSeverity as HermesIssueSeverity,
    HermesProcessStatus as HermesProcessStatus,
    HermesProcessingIssue as HermesProcessingIssue,
    HermesRevisionProcessResponse as HermesRevisionProcessResponse,
    HermesRevisionProcessResult as HermesRevisionProcessResult,
    HermesWikiChange as HermesWikiChange,
    HermesWikiChangeAction as HermesWikiChangeAction,
    WikiExportFile as WikiExportFile,
    WikiExportResponse as WikiExportResponse,
)
from app.domain_models.canon import (
    CanonEntity as CanonEntity,
    CanonEntityCreate as CanonEntityCreate,
    CanonEntityType as CanonEntityType,
    CanonEntityUpdate as CanonEntityUpdate,
)
from app.domain_models.compiler import (
    CanonExtractionReport as CanonExtractionReport,
    CompileRunInfo as CompileRunInfo,
    SceneParseReport as SceneParseReport,
    SceneProposal as SceneProposal,
    SceneProposalAcceptRequest as SceneProposalAcceptRequest,
    SceneProposalAcceptanceReport as SceneProposalAcceptanceReport,
    SceneProposalCreate as SceneProposalCreate,
    SceneProposalStatus as SceneProposalStatus,
    SceneProposalStatusUpdate as SceneProposalStatusUpdate,
)
from app.domain_models.graph import (
    GraphAnalysisResponse as GraphAnalysisResponse,
    GraphAnalysisSummary as GraphAnalysisSummary,
    GraphEdge as GraphEdge,
    GraphEdgeType as GraphEdgeType,
    GraphNode as GraphNode,
    GraphNodeType as GraphNodeType,
    GraphRisk as GraphRisk,
    GraphRiskSeverity as GraphRiskSeverity,
)
from app.domain_models.manuscript import (
    ChapterCompileResponse as ChapterCompileResponse,
    LegacyManuscriptImportCreate as LegacyManuscriptImportCreate,
    ManuscriptChapter as ManuscriptChapter,
    ManuscriptChapterCreate as ManuscriptChapterCreate,
    ManuscriptChapterUpdate as ManuscriptChapterUpdate,
    ManuscriptExportResponse as ManuscriptExportResponse,
    ManuscriptGenerationReview as ManuscriptGenerationReview,
    ManuscriptProposal as ManuscriptProposal,
    ManuscriptProposalAcceptance as ManuscriptProposalAcceptance,
    ManuscriptProposalCreate as ManuscriptProposalCreate,
    ManuscriptProposalSource as ManuscriptProposalSource,
    ManuscriptProposalStatus as ManuscriptProposalStatus,
    ManuscriptProposalStatusUpdate as ManuscriptProposalStatusUpdate,
    ManuscriptRevision as ManuscriptRevision,
    ManuscriptRevisionDiff as ManuscriptRevisionDiff,
    ManuscriptScene as ManuscriptScene,
    ManuscriptSceneUpdate as ManuscriptSceneUpdate,
)
from app.domain_models.memory import (
    MemoryRecord as MemoryRecord,
    MemoryRecordCreate as MemoryRecordCreate,
    MemoryRecordType as MemoryRecordType,
    MemoryRecordUpdate as MemoryRecordUpdate,
)
from app.domain_models.model import (
    GenerationAttempt as GenerationAttempt,
    GenerationAttemptCreate as GenerationAttemptCreate,
    GenerationAttemptKind as GenerationAttemptKind,
    GenerationAttemptStatus as GenerationAttemptStatus,
    GenerationRun as GenerationRun,
    GenerationRunCreate as GenerationRunCreate,
    GenerationRunStatus as GenerationRunStatus,
    GenerationRunUpdate as GenerationRunUpdate,
    ModelCapabilitiesView as ModelCapabilitiesView,
    ModelExecutionOptions as ModelExecutionOptions,
    ModelProfileView as ModelProfileView,
    ProviderGenerationRequest as ProviderGenerationRequest,
    WorkflowAgentTrace as WorkflowAgentTrace,
    WorkflowRuntimeKind as WorkflowRuntimeKind,
    WorkflowRuntimeStatus as WorkflowRuntimeStatus,
    WorkflowRuntimeType as WorkflowRuntimeType,
)
from app.domain_models.narrative import (
    CharacterKnowledge as CharacterKnowledge,
    CharacterKnowledgeCreate as CharacterKnowledgeCreate,
    KnowledgeScope as KnowledgeScope,
    KnowledgeState as KnowledgeState,
    KnowledgeStateAuthorCreate as KnowledgeStateAuthorCreate,
    KnowledgeStateCorrection as KnowledgeStateCorrection,
    KnowledgeStateCreate as KnowledgeStateCreate,
    NarrativeChangeReason as NarrativeChangeReason,
    NarrativeRelation as NarrativeRelation,
    NarrativeRelationCreate as NarrativeRelationCreate,
    NarrativeRelationStatus as NarrativeRelationStatus,
    NarrativeRevision as NarrativeRevision,
    NarrativeVersionChange as NarrativeVersionChange,
    StoryFact as StoryFact,
    StoryFactCorrection as StoryFactCorrection,
    StoryFactCreate as StoryFactCreate,
    StoryFactStatus as StoryFactStatus,
    StoryStateResponse as StoryStateResponse,
    StoryThread as StoryThread,
    StoryThreadAction as StoryThreadAction,
    StoryThreadCreate as StoryThreadCreate,
    StoryThreadEvent as StoryThreadEvent,
    StoryThreadEventCreate as StoryThreadEventCreate,
    StoryThreadStatus as StoryThreadStatus,
    StoryThreadStatusUpdate as StoryThreadStatusUpdate,
    StoryThreadType as StoryThreadType,
)
from app.domain_models.project import (
    HealthResponse as HealthResponse,
    ProjectCreate as ProjectCreate,
    ProjectSummary as ProjectSummary,
)
from app.domain_models.reference import (
    ReferenceEditorContext as ReferenceEditorContext,
    ReferenceGenerationRequest as ReferenceGenerationRequest,
    ReferenceScopeType as ReferenceScopeType,
    ReferenceSuggestion as ReferenceSuggestion,
    ReferenceSuggestionCreate as ReferenceSuggestionCreate,
    ReferenceSuggestionStatus as ReferenceSuggestionStatus,
    ReferenceSuggestionStatusUpdate as ReferenceSuggestionStatusUpdate,
    ReferenceSuggestionType as ReferenceSuggestionType,
)
from app.domain_models.scene import (
    SceneContract as SceneContract,
    SceneContractCreate as SceneContractCreate,
    SceneContractUpdate as SceneContractUpdate,
)
from app.domain_models.snowflake import (
    SnowflakeArtifact as SnowflakeArtifact,
    SnowflakeArtifactHead as SnowflakeArtifactHead,
    SnowflakeArtifactRevision as SnowflakeArtifactRevision,
    SnowflakeArtifactRevisionCreate as SnowflakeArtifactRevisionCreate,
    SnowflakeArtifactRevisionPatch as SnowflakeArtifactRevisionPatch,
    SnowflakeArtifactUpdate as SnowflakeArtifactUpdate,
    SnowflakeDecision as SnowflakeDecision,
    SnowflakeGeneratedRecord as SnowflakeGeneratedRecord,
    SnowflakeGeneratedRecordSet as SnowflakeGeneratedRecordSet,
    SnowflakeGenerationCreate as SnowflakeGenerationCreate,
    SnowflakeGenerationRequest as SnowflakeGenerationRequest,
    SnowflakeGenerationResponse as SnowflakeGenerationResponse,
    SnowflakeHeadState as SnowflakeHeadState,
    SnowflakeManuscriptProgress as SnowflakeManuscriptProgress,
    SnowflakeRecordDecisionRequest as SnowflakeRecordDecisionRequest,
    SnowflakeRecordDecisionResponse as SnowflakeRecordDecisionResponse,
    SnowflakeRecordHead as SnowflakeRecordHead,
    SnowflakeRecordPage as SnowflakeRecordPage,
    SnowflakeRecordRevision as SnowflakeRecordRevision,
    SnowflakeRecordRevisionCreate as SnowflakeRecordRevisionCreate,
    SnowflakeRecordState as SnowflakeRecordState,
    SnowflakeRevisionDecisionRequest as SnowflakeRevisionDecisionRequest,
    SnowflakeRevisionDecisionResponse as SnowflakeRevisionDecisionResponse,
    SnowflakeRevisionPage as SnowflakeRevisionPage,
    SnowflakeRevisionSource as SnowflakeRevisionSource,
    SnowflakeRevisionStatus as SnowflakeRevisionStatus,
    SnowflakeStep as SnowflakeStep,
    SnowflakeStepState as SnowflakeStepState,
    SnowflakeValidationFinding as SnowflakeValidationFinding,
    SnowflakeValidationReport as SnowflakeValidationReport,
    ValidationSeverity as ValidationSeverity,
    ValidationStatus as ValidationStatus,
)
from app.domain_models.writeback import (
    WritebackAction as WritebackAction,
    WritebackProposal as WritebackProposal,
    WritebackProposalCreate as WritebackProposalCreate,
    WritebackProposalStatus as WritebackProposalStatus,
    WritebackProposalStatusUpdate as WritebackProposalStatusUpdate,
    WritebackTarget as WritebackTarget,
)
from app.snowflake.contracts import ManuscriptSceneDraftContract as ManuscriptSceneDraftContract
